version: '3'
name: avalanche-backend
services:
  sut:
    build: .
    links:
    - gateway
    - usermanagement
    - ryce
    - zacr
    - africa
    - domain_watch
  # Gateway
  gateway:
    build: ./gateway
    ports:
      - 4000:4000
    container_name: gateway
    restart: always
    environment:
      NODE_ENV: production
      HOST: gateway
      PORT: 4000
      UM_HOST: usermanagement
      ZACR_HOST: zacr
      AFRICA_HOST: africa
      RYCE_HOST: ryce
      REDIS_HOST: '192.168.6.90'
      REDIS_PORT: 6000
  # User Management
  usermanagement:
    build: ./user-management
    ports:
      - 4001:4001
    container_name: usermanagement
    depends_on:
      - gateway
    environment:
      NODE_ENV: production
      HOST: usermanagement
      PORT: 4001
      REDIS_HOST: '192.168.6.90'
      REDIS_PORT: 6000
      GOOGLE_PASSWORD: 'snlfvyltleqsmmxg'
      POSTGRES_HOST: '192.168.6.90'
      POSTGRES_PORT: 5432
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'FQ@hA!oHJraLZhKv3mN*'
      POSTGRES_DB: 'users'
      JWT_SECRET: '6s93jka$#JHGhjs02KLJSfj4209sdffsSDFGag"'
  # ZACR
  zacr:
    build: ./zacr
    ports:
      - 4002:4002
    container_name: zacr
    depends_on:
      - gateway
    environment:
      NODE_ENV: production
      REDIS_HOST: '192.168.6.90'
      REDIS_PORT: 6000
      HOST: zacr
      PORT: 4002
      GOOGLE_PASSWORD: 'snlfvyltleqsmmxg'
      SNOWFLAKE_ACCOUNT: 'px34381.eu-central-1'
      SNOWFLAKE_USERNAME: 'SKUNKWORKS_USER'
      SNOWFLAKE_PASSWORD: '211vEdMm7H#6'
      SNOWFLAKE_ROLE: 'SKUNKWORKS_ROLE'
      SNOWFLAKE_WAREHOUSE: 'SKUNKWORKS_WH'
      SNOWFLAKE_DATABASE: 'SKUNKWORKS_DB'
      SNOWFLAKE_SCHEMA: 'PUBLIC'
      JWT_SECRET: '6s93jka$#JHGhjs02KLJSfj4209sdffsSDFGag"'
  # ryce
  ryce:
    build: ./ryce
    ports:
      - 4004:4004
    container_name: ryce
    depends_on:
      - gateway
    environment:
      NODE_ENV: production
      REDIS_HOST: '192.168.6.90'
      REDIS_PORT: 6000
      HOST: ryce
      GOOGLE_PASSWORD: 'snlfvyltleqsmmxg'
      SNOWFLAKE_ACCOUNT: 'gf71425.eu-central-1'
      SNOWFLAKE_USERNAME: 'SKUNKWORKS_USER'
      SNOWFLAKE_PASSWORD: 'qr74lW9S6mD&'
      SNOWFLAKE_ROLE: 'SKUNKWORKS_ROLE'
      SNOWFLAKE_WAREHOUSE: 'SKUNKWORKS_WH'
      SNOWFLAKE_DATABASE: 'SKUNKWORKS_DB'
      SNOWFLAKE_SCHEMA: 'PUBLIC'
      JWT_SECRET: '6s93jka$#JHGhjs02KLJSfj4209sdffsSDFGag"'
  # africa
  africa:
    build: ./africa
    ports:
      - 4005:4005
    container_name: africa
    depends_on:
      - gateway
    environment:
      NODE_ENV: production
      REDIS_HOST: '192.168.6.90'
      REDIS_PORT: 6000
      HOST: africa
      GOOGLE_PASSWORD: 'snlfvyltleqsmmxg'
      SNOWFLAKE_ACCOUNT: 'gf71425.eu-central-1'
      SNOWFLAKE_USERNAME: 'SKUNKWORKS_USER'
      SNOWFLAKE_PASSWORD: 'qr74lW9S6mD&'
      SNOWFLAKE_ROLE: 'SKUNKWORKS_ROLE'
      SNOWFLAKE_WAREHOUSE: 'SKUNKWORKS_WH'
      SNOWFLAKE_DATABASE: 'SKUNKWORKS_DB'
      SNOWFLAKE_SCHEMA: 'PUBLIC'
      JWT_SECRET: '6s93jka$#JHGhjs02KLJSfj4209sdffsSDFGag"'
  # domain watch
  domain_watch:
    build: ./Services/DomainWatch/domain_watch
    container_name: DomainWatch
    ports:
      - 4100:4100
    depends_on:
      - gateway
    environment:
      NODE_ENV: production
volumes:
  cache:
    driver: local