name: Code Analysis

on:
  push:
    branches:
      - working
      - stable
  pull_request:
    branches:
      - working
      - stable
  workflow_dispatch:

permissions:
  pull-requests: read
jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=COS301-SE-2023_Avalanche
            -Dsonar.organization=cos301-se-2023
  # CodeCov:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Upload coverage reports to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         files: ./frontend/coverage
  #         token: ${{ secrets.CODECOV_TOKEN }}
