name: Node.js CI

on:
  push:
    branches: [ "working", "stable", "backend_coverage_dev", "integration_dev"]

jobs:
  build:
    if: contains(github.event.head_commit.message, '_TEST_')
    name: Test Domain Watch
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        service: ['gateway', 'zacr', 'user-management', 'domain-watch']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
      env:
        CI: true
    - name: Report Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
        name: codecov-gateway
        fail_ci_if_error: true
