name: Java CI

on:
  push:
    branches:
      - 'backend_dns_watch'

jobs:
  
  test:
    if: contains(github.event.head_commit.message, '_COV_')
    name: Test Domain Watch
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Code Coverage with Maven
        working-directory: ./Services/DomainWatch/domain_watch
        run: mvn jacoco:prepare-agent test install jacoco:report