name: Java Coverage

on:
  push:
    branches:
      - 'backend_dns_watch'

jobs:
  
  test:
    if: contains(github.event.head_commit.message, '_COV_')
    name: Coverage for Domain Watch
    permissions: write-all
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Code Coverage with Maven
        working-directory: ./Services/DomainWatch/domain_watch
        run: mvn jacoco:prepare-agent test install jacoco:report
          
      # generates coverage-report.md and publishes as checkrun
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: Services\DomainWatch\domain_watch\target\site\jacoco\jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: Domain Watch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 75
          fail_below_threshold: true
          publish_only_summary: false
            
            # Publish Coverage Job Summary  # Optional
      - name: Add Coverage Job Summary
        run: echo "${{steps.jacoco_reporter.outputs.coverage_percentage}}" >> $GITHUB_STEP_SUMMARY
                
            # uploads the coverage-report.md artifact  # Optional
      
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-markdown
          path: '*/coverage-results.md' 
          retention-days: 1  
      
