name: Java Tests

on:
  push:
    branches:
      - 'backend_dns_watch'
      - 'working'
      - 'stable'

jobs:
  
  test:
    if: contains(github.event.head_commit.message, '_TEST_') || github.ref === "working" || github.ref === "stable"
    name: Test Domain Watch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Test with Maven
        working-directory: ./Services/DomainWatch/domain_watch
        run: mvn test
