name: NestJS Coverage and SonarCloud Analysis

on:
  push:
    branches: [ "working", "stable", "integration_dev" ]

jobs:
  test:
    name: Coverage for Nest.js Services
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [gateway, user-management, zacr]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      # Running tests with coverage for each service
      - name: Run Jest with coverage
        run: |
          cd ${{ matrix.service }}
          yarn jest --coverage

      # generates coverage-report.md and publishes as checkrun
      - name: Istanbul Code Coverage Report
        id: istanbul_reporter
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: '${{ matrix.service}}/coverage/lcov.info'

      # Publish Coverage Job Summary  # Optional
      - name: Add Coverage Job Summary
        run: echo "${{ steps.istanbul_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
                
      # uploads the coverage-report.md artifact  # Optional
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-markdown
          path: '${{ matrix.service}}/coverage/coverage-results.md' 
          retention-days: 1  

      # SonarCloud analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: './${{ matrix.service }}'
